Repository magento/magento2-login-as-customer, pull requests merged in 2020-04, with the labels that each got.

#68 login-as-customer/issues/59: Customer data not invalidated private content after logged in
  etc/frontend/sections.xml
Labels: Partner: Balance Internet, partners-contribution

#23 Removed "Login As Customer" action from Orders & Customers grid
  app/code/Magento/LoginAsCustomer/Ui/Component/Listing/Column/Login.php
  app/code/Magento/LoginAsCustomer/view/adminhtml/ui_component/customer_listing.xml
  app/code/Magento/LoginAsCustomer/view/adminhtml/ui_component/sales_order_grid.xml
Labels: Award: category of expertise

#69 #55 : Need to update/change titles for ACL resource tree related to Login as Customer
  app/code/Magento/LoginAsCustomer/etc/acl.xml
Labels: Event: Global-Contribution-Day

#47 17 notification banner
  app/code/Magento/LoginAsCustomer/CustomerData/LoginAsCustomer.php
  app/code/Magento/LoginAsCustomer/ViewModel/Configuration.php
  app/code/Magento/LoginAsCustomer/etc/frontend/di.xml
  app/code/Magento/LoginAsCustomer/i18n/en_US.csv
  app/code/Magento/LoginAsCustomer/view/frontend/layout/default.xml
  app/code/Magento/LoginAsCustomer/view/frontend/templates/html/notices.phtml
  app/code/Magento/LoginAsCustomer/view/frontend/templates/html/notices/logout-link.phtml
  app/code/Magento/LoginAsCustomer/view/frontend/web/css/source/_module.less
  app/code/Magento/LoginAsCustomer/view/frontend/web/images/close.svg
  app/code/Magento/LoginAsCustomer/view/frontend/web/images/magento-icon.svg
  app/code/Magento/LoginAsCustomer/view/frontend/web/js/view/loginAsCustomer.js
Labels: Award: category of expertise

#87 17 Notification banner on storefront [fixed: The banner is not showing]
  app/code/Magento/LoginAsCustomer/view/frontend/web/js/login.js
Labels: Award: bug fix, Award: category of expertise

#98 Refactor LoginAsCustomer Login Model
  app/code/Magento/LoginAsCustomer/Api/AuthenticateCustomerInterface.php
  app/code/Magento/LoginAsCustomer/Api/CreateSecretInterface.php
  app/code/Magento/LoginAsCustomer/Api/DeleteOldSecretsInterface.php
  app/code/Magento/LoginAsCustomer/Api/DeleteSecretInterface.php
  app/code/Magento/LoginAsCustomer/Api/GetAuthenticateDataInterface.php
  app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Index.php
  app/code/Magento/LoginAsCustomer/Controller/Adminhtml/Login/Login.php
  app/code/Magento/LoginAsCustomer/Controller/Login/Index.php
  app/code/Magento/LoginAsCustomer/Cron/DeleteOldSecrets.php
  app/code/Magento/LoginAsCustomer/Model/AuthenticateCustomer.php
  app/code/Magento/LoginAsCustomer/Model/Config.php
  app/code/Magento/LoginAsCustomer/Model/Login.php
  app/code/Magento/LoginAsCustomer/Model/ResourceModel/CreateSecret.php
  app/code/Magento/LoginAsCustomer/Model/ResourceModel/DeleteOldSecrets.php
  app/code/Magento/LoginAsCustomer/Model/ResourceModel/DeleteSecret.php
  app/code/Magento/LoginAsCustomer/Model/ResourceModel/GetAuthenticateData.php
  app/code/Magento/LoginAsCustomer/Model/ResourceModel/Login.php
  app/code/Magento/LoginAsCustomer/etc/crontab.xml
  app/code/Magento/LoginAsCustomer/etc/db_schema.xml
  app/code/Magento/LoginAsCustomer/etc/db_schema_whitelist.json
  app/code/Magento/LoginAsCustomer/etc/di.xml
Labels: Award: category of expertise

#99 Moved code related to the shopping cart from LoginAsCustomer to LogiAsCustomerSales extension
  app/code/Magento/LoginAsCustomer/Model/AuthenticateCustomer.php
  app/code/Magento/LoginAsCustomer/composer.json
  app/code/Magento/LoginAsCustomerSales/Plugin/AuthenticateCustomer.php
  app/code/Magento/LoginAsCustomerSales/README.md
  app/code/Magento/LoginAsCustomerSales/composer.json
  app/code/Magento/LoginAsCustomerSales/etc/di.xml
  app/code/Magento/LoginAsCustomerSales/etc/module.xml
  app/code/Magento/LoginAsCustomerSales/registration.php
Labels: Award: category of expertise

#109 [WIP]Log admin actions with Login as Customer.
  app/code/Magento/LoginAsCustomerLog/Api/Data/LogInterface.php
  app/code/Magento/LoginAsCustomerLog/Api/Data/LogSearchResultsInterface.php
  app/code/Magento/LoginAsCustomerLog/Api/GetLogsListInterface.php
  app/code/Magento/LoginAsCustomerLog/Api/SaveLogsInterface.php
  app/code/Magento/LoginAsCustomerLog/Block/Adminhtml/Login.php
  app/code/Magento/LoginAsCustomerLog/Controller/Adminhtml/Log/Index.php
  app/code/Magento/LoginAsCustomerLog/Controller/Adminhtml/Login/Grid.php
  app/code/Magento/LoginAsCustomerLog/Controller/Adminhtml/Login/Index.php
  app/code/Magento/LoginAsCustomerLog/Model/GetLogList.php
  app/code/Magento/LoginAsCustomerLog/Model/Log.php
  app/code/Magento/LoginAsCustomerLog/Model/LogSearchResults.php
  app/code/Magento/LoginAsCustomerLog/Model/Login.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Log.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Log/Collection.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login/Collection.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/Login/Grid/Collection.php
  app/code/Magento/LoginAsCustomerLog/Model/ResourceModel/SaveLogs.php
  app/code/Magento/LoginAsCustomerLog/Plugin/LoginAsCustomerApi/Api/AuthenticateCustomerInterface/LogAuthenticationPlugin.php
  app/code/Magento/LoginAsCustomerLog/Ui/DataProvider/LogDataProvider.php
  app/code/Magento/LoginAsCustomerLog/composer.json
  app/code/Magento/LoginAsCustomerLog/etc/acl.xml
  app/code/Magento/LoginAsCustomerLog/etc/adminhtml/menu.xml
  app/code/Magento/LoginAsCustomerLog/etc/adminhtml/routes.xml
  app/code/Magento/LoginAsCustomerLog/etc/db_schema.xml
  app/code/Magento/LoginAsCustomerLog/etc/db_schema_whitelist.json
  app/code/Magento/LoginAsCustomerLog/etc/di.xml
  app/code/Magento/LoginAsCustomerLog/etc/frontend/di.xml
  app/code/Magento/LoginAsCustomerLog/view/adminhtml/layout/loginascustomer_log_log_index.xml
  app/code/Magento/LoginAsCustomerLog/view/adminhtml/layout/loginascustomer_login_grid.xml
  app/code/Magento/LoginAsCustomerLog/view/adminhtml/layout/loginascustomer_login_grid_block.xml
  app/code/Magento/LoginAsCustomerLog/view/adminhtml/ui_component/login_as_customer_log_listing.xml
Labels: Progress: review

#119 Confirmation pop-up window for "Login as Customer" (New Request)
  app/code/Magento/LoginAsCustomerUi/Block/Adminhtml/ConfirmationPopup.php
  app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Login.php
  app/code/Magento/LoginAsCustomerUi/Controller/Adminhtml/Login/Manual.php
  app/code/Magento/LoginAsCustomerUi/Plugin/Button/ToolbarPlugin.php
  app/code/Magento/LoginAsCustomerUi/Ui/Customer/Component/Control/LoginAsCustomerButton.php
  app/code/Magento/LoginAsCustomerUi/Ui/Store/DataProvider/Form/StoreDataProvider.php
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/adminhtml_order_shipment_view.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/customer_index_edit.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/loginascustomer_confirmation_popup.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/loginascustomer_login_manual.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/sales_order_creditmemo_view.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/sales_order_invoice_view.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/layout/sales_order_view.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/templates/confirmation-popup.phtml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/ui_component/manual_store_form.xml
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/web/css/source/_module.less
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/web/js/confirmation-popup.js
  app/code/Magento/LoginAsCustomerUi/view/adminhtml/web/template/confirmation-popup/store-view-ptions.html
Labels: Award: category of expertise

#123 Added spinner/loader while Admin is logging in as Customer
  app/code/Magento/LoginAsCustomerPageCache/etc/adminhtml/system.xml
  app/code/Magento/LoginAsCustomerUi/Block/Adminhtml/ConfirmationPopup.php
  app/code/Magento/LoginAsCustomerUi/Controller/Login/Index.php
  app/code/Magento/LoginAsCustomerUi/Controller/Login/Proceed.php
  app/code/Magento/LoginAsCustomerUi/Model/Config/Source/StoreViewLogin.php
  app/code/Magento/LoginAsCustomerUi/Plugin/Button/ToolbarPlugin.php
  app/code/Magento/LoginAsCustomerUi/Ui/Customer/Component/Control/LoginAsCustomerButton.php
  app/code/Magento/LoginAsCustomerUi/etc/adminhtml/system.xml
  app/code/Magento/LoginAsCustomerUi/view/frontend/layout/loginascustomer_login_index.xml
  app/code/Magento/LoginAsCustomerUi/view/frontend/web/js/login.js
Labels: Award: category of expertise
